name: e_commerce_num2
description: A Flutter project.



publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  get_storage: ^2.0.3
  sqflite: ^2.0.3
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  share_plus: ^4.0.10+1
  package_info:

  
  #Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.0
  cloud_firestore: ^3.4.1
  firebase_storage: ^10.3.4
  firebase_dynamic_links: ^4.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

